name: Auto Update Data Karhutla

on:
  schedule:
    # Berjalan otomatis jam 07:00 WITA (23:00 UTC) & jam 13:00 WITA (05:00 UTC)
    - cron: '0 23,5 * * *'
  workflow_dispatch: # Menyediakan tombol 'Run Manual'

permissions:
  contents: write # Memberikan izin push secara eksplisit

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run Script Scraper
        run: python main.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Automation"
          git config --global user.email "actions@github.com"
          git add data_karhutla.json
          git commit -m "Auto-update data karhutla [skip ci]" || exit 0
          git push
